v1

diff --git a/server/ubuntu/usr/bin/sensible-browser b/server/ubuntu/usr/bin/sensible-browser
--- a/server/ubuntu/usr/bin/sensible-browser
+++ b/server/ubuntu/usr/bin/sensible-browser
@@ -1,16 +1,24 @@
 #!/bin/sh
 
+PATH="$PATH:/usr/share/sensible-utils/bin"
 # Prevent recursive loops, where these values are set to this script
-p="$(which sensible-browser)"
-[ -n "$BROWSER" ] && [ "$(which $BROWSER || true)" = "$p" ] && BROWSER=
+program="$(realpath "$(command -v "$0")")"
 
-if test -n "$BROWSER"; then
-    ${BROWSER} "$@"
-    ret="$?"
-    if [ "$ret" -ne 126 ] && [ "$ret" -ne 127 ]; then
-	exit "$ret"
-    fi
-fi
+Try()
+{
+    # global $candidate
+    [ -z "$candidate" ] && return
+    # Prevent recursive loops, where environment variables are set to this script
+    [ x$(realpath "$(command -v "$candidate" || true)" || true) = "x$program" ] && return
+    # interpret like environ (7) man page. Do not use eval in order to not leak variables
+    sh -c "$candidate \"\$@\"" EDITOR "$@"
+    ret=$?
+    # Operating system command not found
+    [ "$ret" -ne 126 ] && [ "$ret" -ne 127 ] && exit "$ret"
+}
+
+candidate="$BROWSER"
+Try "$@"
 
 if test -n "$DISPLAY"; then
     if test -n "$GNOME_DESKTOP_SESSION_ID"; then
@@ -31,6 +39,6 @@ elif test -x /usr/bin/www-browser; then
     exec /usr/bin/www-browser "$@"
 fi
 
-printf "Couldn't find a suitable web browser!\n" >&2
-printf "Set the BROWSER environment variable to your desired browser.\n" >&2
-exit 1;
+echo "Couldn't find a suitable web browser!" >&2
+echo "Set the BROWSER environment variable to your desired browser." >&2
+exit 1
